app/__init__.py
import os

from flask import Flask, g, request
from flask_bootstrap import Bootstrap
from flask_babel import Babel

babel = Babel()

def create_app(config):

    # build app configuration
    app = Flask(__name__)
    app.config.from_object(config)
    bootstrap = Bootstrap(app)

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    @app.route('/hello')
    def hello():
        return 'Hello World!'

    # init db
    from . import db
    db.init_app(app)

    # init babel
    from . import i18n
    i18n.init_app(app)

    # auth routes
    from .views import auth
    app.register_blueprint(auth.bp)

    # users routes
    from .views import users
    app.register_blueprint(users.bp)
    app.add_url_rule('/', endpoint='index')

    return app

app/views/auth.py
from flask import (
    Blueprint,
    render_template,
    request,
    redirect,
    url_for,
    flash,
    session,
    g,
)
from app.db import get_db, User
from werkzeug.security import check_password_hash, generate_password_hash
from app.validate import AccountForm, LoginForm
from functools import wraps

bp = Blueprint('auth', __name__, url_prefix='/<lang_code>/auth')

# 在每次收到 request 時檢查前端 session 是否帶有 user_id，有的話則將用戶存於 g.user
@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        db = get_db()
        g.user = User.query.filter_by(id=user_id).first()

# 建立一個 decorator 來驗證使用者是否已登入
def login_required(view):
    @wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))

        return view(**kwargs)

    return wrapped_view

@bp.route('/register', methods=('GET', 'POST'))
def register():
    form = AccountForm(request.form)
    if request.method == 'POST' and form.validate_on_submit():
        firstname = request.form['firstname']
        lastname = request.form['lastname']
        email = request.form['email']
        password = request.form['password']
        db = get_db()
        error = None

        if User.query.filter_by(email=email).first() is not None:
            error = f"User {email} is already registered."

        if error is None:
            print('add a user')
            user = User(
                firstname,
                lastname,
                email,
                generate_password_hash(password)
            )
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('auth.login'))

        flash(error)

    return render_template('auth/register.html', form=form)

@bp.route('/login', methods=('GET', 'POST'))
def login():
    form = LoginForm(request.form)
    if request.method == 'POST' and form.validate_on_submit():
        print('check')
        email = request.form['email']
        password = request.form['password']
        db = get_db()
        error = None
        user = User.query.filter_by(email=email).first()

        if user is None:
            error = 'User not found'
        elif not check_password_hash(user.password, password):
            error = 'Incorrect password'

        if error is None:
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('users.index'))

        flash(error)

    return render_template('auth/login.html', form=form)

@bp.route('/logout')
def logout():
    print('logout')
    session.clear()
    return redirect(url_for('users.index'))

app/views/users.py
from flask import (
    Blueprint,
    render_template,
    request,
    url_for,
    redirect
)
from app.db import get_db, User
from app.views.auth import login_required

bp = Blueprint('users', __name__, url_prefix='/<lang_code>/users')

@bp.route('/')
def index():
    db = get_db()
    users = User.query.all()

    return render_template('users/index.html', users=users)

@bp.route('/delete/<int:user_id>', methods=('GET', 'POST'))
@login_required
def delete_user(user_id):
    if request.method == 'POST':
        db = get_db()
        user = User.query.filter_by(id=user_id).first()
        db.session.delete(user)
        db.session.commit()
        return redirect(url_for('users.index'))

    return render_template('users/index.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HiTrustAI</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<body>
    <!-- Nav bar -->
    <nav class="navbar navbar-light bg-light mb-3">
        <div class="container-fluid">
            <a href="{{ url_for('users.index') }}" class="navbar-brand">DiiA {{ _('Admin') }}</a>
            <div class="d-flex">
                <ul class="nav">
                  {% if g.user %}
                    <span class="navbar-text">
                      Hello, {{ g.user['firstname'] }}!
                    </span>
                    <li class="nav-item">
                      <a class="nav-link active" aria-current="page" href="{{ url_for('auth.logout') }}">{{ _('Logout') }}</a>
                    </li>
                  {% else %}
                    <li class="nav-item">
                      <a class="nav-link active" aria-current="page" href="{{ url_for('auth.register') }}">{{ _('Register') }}</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{{ url_for('auth.login') }}">{{ _('Login') }}</a>
                    </li>
                  {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <!-- Flash error -->
    {% for message in get_flashed_messages() %}
        <div class="alert alert-success alert-dismissible fade show m-3" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}

    <!-- Form -->
    {% block content %}{% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
</body>

</html>

app/templates/jinja_helpers.html
{% macro render_field(field) %}
    <div class="form-group">
        {{ field.label(class="form-control-label") }}
        {% if field.errors %}
            {{ field(class="form-control is-invalid") }}
            <div class="invalid-feedback">
                {% for error in field.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
        {% else %}
            {{ field(class="form-control") }}
        {% endif %}
    </div>
{% endmacro %}

app/templates/users/index.html
{% extends 'base.html' %}

{% block content %}
{% if g.user %}
    <div class="col-8 offset-2">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">{{ _('Username') }}</th>
                    <th scope="col">{{ _('Email') }}</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                    <tr>
                        <th scope="row">{{ user["id"] }}</th>
                        <td>{{ user["firstname"] }}, {{ user["lastname"] }}</td>
                        <td>{{ user["email"] }}</td>
                        <td>
                            <form action="{{ url_for('users.delete_user', user_id=user.id) }}" method="POST">
                                <button class="btn btn-danger btn-sm">Delete</button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endif %}
{% endblock %}